# -*- coding: utf-8 -*-
"""Display names for the MonkeyQt theme selector."""

DEFAULT_THEME_CN_NAME = "MonkeyQt 默认样式"

THEME_CN_NAMES = {
    "Elegant Light": "雅致亮色",
    "Minimalism & Swiss Style": "极简瑞士风格",
    "Neumorphism": "新拟物化",
    "Glassmorphism": "玻璃拟态",
    "Brutalism": "粗野主义",
    "3D & Hyperrealism": "3D 与超现实",
    "Vibrant & Block-based": "活力板块风",
    "Dark Mode (OLED)": "深色模式 OLED",
    "Accessible & Ethical": "无障碍与伦理设计",
    "Claymorphism": "黏土拟态",
    "Aurora UI": "极光 UI",
    "Retro-Futurism": "复古未来主义",
    "Flat Design": "扁平化设计",
    "Skeuomorphism": "写实拟物化",
    "Liquid Glass": "流态玻璃",
    "Motion-Driven": "动效驱动",
    "Micro-interactions": "微交互风格",
    "Inclusive Design": "包容性设计",
    "Zero Interface": "无感零界面",
    "Soft UI Evolution": "柔和 UI 演进",
    "Hero-Centric Design": "大图主角设计",
    "Conversion-Optimized": "转化率优化设计",
    "Feature-Rich Showcase": "功能特性展示",
    "Minimal & Direct": "极简直达设计",
    "Social Proof-Focused": "社交信誉焦点",
    "Interactive Product Demo": "交互产品演示",
    "Trust & Authority": "信任与权威设计",
    "Storytelling-Driven": "故事叙事驱动",
    "Data-Dense Dashboard": "高密度数据看板",
    "Heat Map & Heatmap Style": "热力图分析风",
    "Executive Dashboard": "决策层仪表盘",
    "Real-Time Monitoring": "实时监控大屏",
    "Drill-Down Analytics": "下钻式深度分析",
    "Comparative Analysis Dashboard": "对比分析看板",
    "Predictive Analytics": "预测性分析风",
    "User Behavior Analytics": "用户行为分析",
    "Financial Dashboard": "财务指标看板",
    "Sales Intelligence Dashboard": "销售智能分析",
    "Neubrutalism": "新粗野主义",
    "Bento Box Grid": "便当盒网格",
    "Y2K Aesthetic": "Y2K 千禧美学",
    "Cyberpunk UI": "赛博朋克 UI",
    "Organic Biophilic": "有机双生设计",
    "AI-Native UI": "AI 原生 UI",
    "Memphis Design": "孟菲斯设计",
    "Vaporwave": "蒸汽波",
    "Dimensional Layering": "多维分层",
    "Exaggerated Minimalism": "夸张极简主义",
    "Kinetic Typography": "动力字体设计",
    "Parallax Storytelling": "视差叙事",
    "Swiss Modernism 2.0": "瑞士现代主义 2.0",
    "HUD / Sci-Fi FUI": "HUD 科幻界面",
    "Pixel Art": "像素艺术",
    "Bento Grids": "便当网格",
    "Spatial UI (VisionOS)": "空间 UI VisionOS",
    "E-Ink / Paper": "电子墨水屏与纸质",
    "Gen Z Chaos / Maximalism": "Z 世代混乱极繁",
    "Biomimetic / Organic 2.0": "仿生有机 2.0",
    "Anti-Polish / Raw Aesthetic": "反精致粗砺美学",
    "Tactile Digital / Deformable UI": "触觉拟真变形 UI",
    "Nature Distilled": "自然提炼色系",
    "Interactive Cursor Design": "交互式光标",
    "Voice-First Multimodal": "语音优先多模态",
    "3D Product Preview": "3D 产品预览",
    "Gradient Mesh / Aurora Evolved": "渐变网格与进化极光",
    "Editorial Grid / Magazine": "社论网格杂志风",
    "Chromatic Aberration / RGB Split": "色差与 RGB 分离",
    "Vintage Analog / Retro Film": "复古模拟胶片",
}


def theme_display_name(name: str) -> str:
    """Return the Chinese display name while keeping the English key for lookup."""
    if name in ("", "__monkeyqt_default__", "MonkeyQt Default"):
        return DEFAULT_THEME_CN_NAME
    return THEME_CN_NAMES.get(name, name)
