# -*- coding: utf-8 -*-
"""
MonkeyQt Theme Tokens — 自动生成，请勿手动编辑
由 scripts/compile_themes.py 从 ui-ux-pro-max styles.csv 编译而来
共 67 套 Design Token
"""


THEME_TOKENS: dict[str, dict] = {
    'Minimalism & Swiss Style': {
        'name': 'Minimalism & Swiss Style',
        'type': 'General',
        'keywords': 'Clean, simple, spacious, functional, white space, high contrast, geometric, sans-serif, grid-based, essential',
        'effects': 'Subtle hover (200-250ms), smooth transitions, sharp shadows if any, clear type hierarchy, fast loading',
        'best_for': 'Enterprise apps, dashboards, documentation sites, SaaS platforms, professional tools',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#000000',
        '--secondary': '#FFFFFF',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '0px',
        '--shadow': 'none',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Neumorphism': {
        'name': 'Neumorphism',
        'type': 'General',
        'keywords': 'Soft UI, embossed, debossed, convex, concave, light source, subtle depth, rounded (12-16px), monochromatic',
        'effects': 'Soft box-shadow (multiple: -5px -5px 15px, 5px 5px 15px), smooth press (150ms), inner subtle shadow',
        'best_for': 'Health/wellness apps, meditation platforms, fitness trackers, minimal interaction UIs',
        'performance': '⚡ Good',
        'accessibility': '⚠ Low contrast',
        'light_mode': '✓ Full',
        'dark_mode': '◐ Partial',
        '--bg': '#F5F5F5',
        '--fg': '#1E293B',
        '--primary': '#C8E0F4',
        '--secondary': '#F5E0E8',
        '--accent': '#E8E8E8',
        '--border': '#E2E8F0',
        '--radius': '14px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Glassmorphism': {
        'name': 'Glassmorphism',
        'type': 'General',
        'keywords': 'Frosted glass, transparent, blurred background, layered, vibrant background, light source, depth, multi-layer',
        'effects': 'Backdrop blur (10-20px), subtle border (1px solid rgba white 0.2), light reflection, Z-depth',
        'best_for': 'Modern SaaS, financial dashboards, high-end corporate, lifestyle apps, modal overlays, navigation',
        'performance': '⚠ Good',
        'accessibility': '⚠ Ensure 4.5:1',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': 'vibrant color',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': 'rgba(255',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '15px',
        '--glow': '',
    },

    'Brutalism': {
        'name': 'Brutalism',
        'type': 'General',
        'keywords': 'Raw, unpolished, stark, high contrast, plain text, default fonts, visible borders, asymmetric, anti-design',
        'effects': 'No smooth transitions (instant), sharp corners (0px), bold typography (700+), visible grid, large blocks',
        'best_for': 'Design portfolios, artistic projects, counter-culture brands, editorial/media sites, tech blogs',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#FF0000',
        '--secondary': '#0000FF',
        '--accent': '#FFFF00',
        '--border': '#E2E8F0',
        '--radius': '0px',
        '--shadow': '',
        '--border-width': '2px',
        '--blur': '',
        '--glow': '',
    },

    '3D & Hyperrealism': {
        'name': '3D & Hyperrealism',
        'type': 'General',
        'keywords': 'Depth, realistic textures, 3D models, spatial navigation, tactile, skeuomorphic elements, rich detail, immersive',
        'effects': 'WebGL/Three.js 3D, realistic shadows (layers), physics lighting, parallax (3-5 layers), smooth 3D (300-400ms)',
        'best_for': 'Gaming, product showcase, immersive experiences, high-end e-commerce, architectural viz, VR/AR',
        'performance': '❌ Poor',
        'accessibility': '⚠ Not accessible',
        'light_mode': '◐ Partial',
        'dark_mode': '◐ Partial',
        '--bg': '#C0C0C0',
        '--fg': '#1E293B',
        '--primary': '#001F3F',
        '--secondary': '#228B22',
        '--accent': '#800020',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Vibrant & Block-based': {
        'name': 'Vibrant & Block-based',
        'type': 'General',
        'keywords': 'Bold, energetic, playful, block layout, geometric shapes, high color contrast, duotone, modern, energetic',
        'effects': 'Large sections (48px+ gaps), animated patterns, bold hover (color shift), scroll-snap, large type (32px+), 200-300ms',
        'best_for': 'Startups, creative agencies, gaming, social media, youth-focused, entertainment, consumer',
        'performance': '⚡ Good',
        'accessibility': '◐ Ensure WCAG',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFAA00',
        '--fg': '#1E293B',
        '--primary': '#39FF14',
        '--secondary': '#BF00FF',
        '--accent': '#FF1493',
        '--border': '#E2E8F0',
        '--radius': '20px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Dark Mode (OLED)': {
        'name': 'Dark Mode (OLED)',
        'type': 'General',
        'keywords': 'Dark theme, low light, high contrast, deep black, midnight blue, eye-friendly, OLED, night mode, power efficient',
        'effects': 'Minimal glow (text-shadow: 0 0 10px), dark-to-light transitions, low white emission, high readability, visible focus',
        'best_for': 'Night-mode apps, coding platforms, entertainment, eye-strain prevention, OLED devices, low-light',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✗ No',
        'dark_mode': '✓ Only',
        '--bg': '#121212',
        '--fg': '#FFFFFF',
        '--primary': '#000000',
        '--secondary': '#121212',
        '--accent': '#0A0E27',
        '--border': '#333333',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': 'minimal',
    },

    'Accessible & Ethical': {
        'name': 'Accessible & Ethical',
        'type': 'General',
        'keywords': 'High contrast, large text (16px+), keyboard navigation, screen reader friendly, WCAG compliant, focus state, semantic',
        'effects': 'Clear focus rings (3-4px), ARIA labels, skip links, responsive design, reduced motion, 44x44px touch targets',
        'best_for': 'Government, healthcare, education, inclusive products, large audience, legal compliance, public',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Claymorphism': {
        'name': 'Claymorphism',
        'type': 'General',
        'keywords': 'Soft 3D, chunky, playful, toy-like, bubbly, thick borders (3-4px), double shadows, rounded (16-24px)',
        'effects': 'Inner+outer shadows (subtle, no hard lines), soft press (200ms ease-out), fluffy elements, smooth transitions',
        'best_for': "Educational apps, children's apps, SaaS platforms, creative tools, fun-focused, onboarding, casual games",
        'performance': '⚡ Good',
        'accessibility': '⚠ Ensure 4.5:1',
        'light_mode': '✓ Full',
        'dark_mode': '◐ Partial',
        '--bg': '#E6E6FA',
        '--fg': '#1E293B',
        '--primary': '#FDBCB4',
        '--secondary': '#ADD8E6',
        '--accent': '#98FF98',
        '--border': '#E2E8F0',
        '--radius': '20px',
        '--shadow': '',
        '--border-width': '3-4px',
        '--blur': '',
        '--glow': '',
    },

    'Aurora UI': {
        'name': 'Aurora UI',
        'type': 'General',
        'keywords': 'Vibrant gradients, smooth blend, Northern Lights effect, mesh gradient, luminous, atmospheric, abstract',
        'effects': 'Large flowing CSS/SVG gradients, subtle 8-12s animations, depth via color layering, smooth morph',
        'best_for': 'Modern SaaS, creative agencies, branding, music platforms, lifestyle, premium products, hero sections',
        'performance': '⚠ Good',
        'accessibility': '⚠ Text contrast',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#00FFFF',
        '--fg': '#1E293B',
        '--primary': '#0080FF',
        '--secondary': '#FF1493',
        '--accent': '#00FFFF',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Retro-Futurism': {
        'name': 'Retro-Futurism',
        'type': 'General',
        'keywords': 'Vintage sci-fi, 80s aesthetic, neon glow, geometric patterns, CRT scanlines, pixel art, cyberpunk, synthwave',
        'effects': 'CRT scanlines (::before overlay), neon glow (text-shadow+box-shadow), glitch effects (skew/offset keyframes)',
        'best_for': 'Gaming, entertainment, music platforms, tech brands, artistic projects, nostalgic, cyberpunk',
        'performance': '⚠ Moderate',
        'accessibility': '⚠ High contrast/strain',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Dark focused',
        '--bg': '#000000',
        '--fg': '#1E293B',
        '--primary': '#0080FF',
        '--secondary': '#FF006E',
        '--accent': '#00FFFF',
        '--border': '#E2E8F0',
        '--radius': '0px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Flat Design': {
        'name': 'Flat Design',
        'type': 'General',
        'keywords': '2D, minimalist, bold colors, no shadows, clean lines, simple shapes, typography-focused, modern, icon-heavy',
        'effects': 'No gradients/shadows, simple hover (color/opacity shift), fast loading, clean transitions (150-200ms ease), minimal icons',
        'best_for': 'Web apps, mobile apps, cross-platform, startup MVPs, user-friendly, SaaS, dashboards, corporate',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '2px',
        '--shadow': 'none',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Skeuomorphism': {
        'name': 'Skeuomorphism',
        'type': 'General',
        'keywords': 'Realistic, texture, depth, 3D appearance, real-world metaphors, shadows, gradients, tactile, detailed, material',
        'effects': 'Realistic shadows (layers), depth (perspective), texture details (noise, grain), realistic animations (300-500ms)',
        'best_for': 'Legacy apps, gaming, immersive storytelling, premium products, luxury, realistic simulations, education',
        'performance': '❌ Poor',
        'accessibility': '⚠ Textures reduce readability',
        'light_mode': '◐ Partial',
        'dark_mode': '◐ Partial',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Liquid Glass': {
        'name': 'Liquid Glass',
        'type': 'General',
        'keywords': 'Flowing glass, morphing, smooth transitions, fluid effects, translucent, animated blur, iridescent, chromatic aberration',
        'effects': 'Morphing elements (SVG/CSS), fluid animations (400-600ms curves), dynamic blur (backdrop-filter), color transitions',
        'best_for': 'Premium SaaS, high-end e-commerce, creative platforms, branding experiences, luxury portfolios',
        'performance': '⚠ Moderate-Poor',
        'accessibility': '⚠ Text contrast',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '15px',
        '--glow': '',
    },

    'Motion-Driven': {
        'name': 'Motion-Driven',
        'type': 'General',
        'keywords': 'Animation-heavy, microinteractions, smooth transitions, scroll effects, parallax, entrance anim, page transitions',
        'effects': 'Scroll anim (Intersection Observer), hover (300-400ms), entrance, parallax (3-5 layers), page transitions',
        'best_for': 'Portfolio sites, storytelling platforms, interactive experiences, entertainment apps, creative, SaaS',
        'performance': '⚠ Good',
        'accessibility': '⚠ Prefers-reduced-motion',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Micro-interactions': {
        'name': 'Micro-interactions',
        'type': 'General',
        'keywords': 'Small animations, gesture-based, tactile feedback, subtle animations, contextual interactions, responsive',
        'effects': 'Small hover (50-100ms), loading spinners, success/error state anim, gesture-triggered (swipe/pinch), haptic',
        'best_for': 'Mobile apps, touchscreen UIs, productivity tools, user-friendly, consumer apps, interactive components',
        'performance': '⚡ Excellent',
        'accessibility': '✓ Good',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#F59E0B',
        '--fg': '#1E293B',
        '--primary': '#22C55E',
        '--secondary': '#EF4444',
        '--accent': '#F59E0B',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Inclusive Design': {
        'name': 'Inclusive Design',
        'type': 'General',
        'keywords': 'Accessible, color-blind friendly, high contrast, haptic feedback, voice interaction, screen reader, WCAG AAA, universal',
        'effects': 'Haptic feedback (vibration), voice guidance, focus indicators (4px+ ring), motion options, alt content, semantic',
        'best_for': 'Public services, education, healthcare, finance, government, accessible consumer, inclusive',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Zero Interface': {
        'name': 'Zero Interface',
        'type': 'General',
        'keywords': 'Minimal visible UI, voice-first, gesture-based, AI-driven, invisible controls, predictive, context-aware, ambient',
        'effects': 'Voice recognition UI, gesture detection, AI predictions (smooth reveal), progressive disclosure, smart suggestions',
        'best_for': 'Voice assistants, AI platforms, future-forward UX, smart home, contextual computing, ambient experiences',
        'performance': '⚡ Excellent',
        'accessibility': '✓ Excellent',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#F5F1E8',
        '--fg': '#1E293B',
        '--primary': '#FAFAFA',
        '--secondary': '#F0F0F0',
        '--accent': '#F5F1E8',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Soft UI Evolution': {
        'name': 'Soft UI Evolution',
        'type': 'General',
        'keywords': 'Evolved soft UI, better contrast, modern aesthetics, subtle depth, accessibility-focused, improved shadows, hybrid',
        'effects': 'Improved shadows (softer than flat, clearer than neumorphism), modern (200-300ms), focus visible, WCAG AA/AAA',
        'best_for': 'Modern enterprise apps, SaaS platforms, health/wellness, modern business tools, professional, hybrid',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA+',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#90EE90',
        '--fg': '#1E293B',
        '--primary': '#87CEEB',
        '--secondary': '#FFB6C1',
        '--accent': '#90EE90',
        '--border': '#E2E8F0',
        '--radius': '10px',
        '--shadow': 'modern blend',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Hero-Centric Design': {
        'name': 'Hero-Centric Design',
        'type': 'Landing Page',
        'keywords': 'Large hero section, compelling headline, high-contrast CTA, product showcase, value proposition, hero image/video, dramatic visual',
        'effects': 'Smooth scroll reveal, fade-in animations on hero, subtle background parallax, CTA glow/pulse effect',
        'best_for': 'SaaS landing pages, product launches, service landing pages, B2B platforms, tech companies',
        'performance': '⚡ Good',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Conversion-Optimized': {
        'name': 'Conversion-Optimized',
        'type': 'Landing Page',
        'keywords': 'Form-focused, minimalist design, single CTA focus, high contrast, urgency elements, trust signals, social proof, clear value',
        'effects': 'Hover states on CTA (color shift, slight scale), form field focus animations, loading spinner, success feedback',
        'best_for': 'E-commerce product pages, free trial signups, lead generation, SaaS pricing pages, limited-time offers',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Feature-Rich Showcase': {
        'name': 'Feature-Rich Showcase',
        'type': 'Landing Page',
        'keywords': 'Multiple feature sections, grid layout, benefit cards, visual feature demonstrations, interactive elements, problem-solution pairs',
        'effects': 'Card hover effects (lift/scale), icon animations on scroll, feature toggle animations, smooth section transitions',
        'best_for': 'Enterprise SaaS, software tools landing pages, platform services, complex product explanations, B2B products',
        'performance': '⚡ Good',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '12px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Minimal & Direct': {
        'name': 'Minimal & Direct',
        'type': 'Landing Page',
        'keywords': 'Minimal text, white space heavy, single column layout, direct messaging, clean typography, visual-centric, fast-loading',
        'effects': 'Very subtle hover effects, minimal animations, fast page load (no heavy animations), smooth scroll',
        'best_for': 'Simple service landing pages, indie products, consulting services, micro SaaS, freelancer portfolios',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Social Proof-Focused': {
        'name': 'Social Proof-Focused',
        'type': 'Landing Page',
        'keywords': 'Testimonials prominent, client logos displayed, case studies sections, reviews/ratings, user avatars, success metrics, credibility markers',
        'effects': 'Testimonial carousel animations, logo grid fade-in, stat counter animations (number count-up), review star ratings',
        'best_for': 'B2B SaaS, professional services, premium products, e-commerce conversion pages, established brands',
        'performance': '⚡ Good',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Interactive Product Demo': {
        'name': 'Interactive Product Demo',
        'type': 'Landing Page',
        'keywords': 'Embedded product mockup/video, interactive elements, product walkthrough, step-by-step guides, hover-to-reveal features, embedded demos',
        'effects': 'Product animation playback, step progression animations, hover reveal effects, smooth zoom on interaction',
        'best_for': 'SaaS platforms, tool/software products, productivity apps landing pages, developer tools, productivity software',
        'performance': '⚠ Good (video/interactive)',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Trust & Authority': {
        'name': 'Trust & Authority',
        'type': 'Landing Page',
        'keywords': 'Certificates/badges displayed, expert credentials, case studies with metrics, before/after comparisons, industry recognition, security badges',
        'effects': 'Badge hover effects, metric pulse animations, certificate carousel, smooth stat reveal',
        'best_for': 'Healthcare/medical landing pages, financial services, enterprise software, premium/luxury products, legal services',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Storytelling-Driven': {
        'name': 'Storytelling-Driven',
        'type': 'Landing Page',
        'keywords': 'Narrative flow, visual story progression, section transitions, consistent character/brand voice, emotional messaging, journey visualization',
        'effects': 'Section-to-section animations, scroll-triggered reveals, character/icon animations, morphing transitions, parallax narrative',
        'best_for': 'Brand/startup stories, mission-driven products, premium/lifestyle brands, documentary-style products, educational',
        'performance': '⚠ Moderate (animations)',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Data-Dense Dashboard': {
        'name': 'Data-Dense Dashboard',
        'type': 'BI/Analytics',
        'keywords': 'Multiple charts/widgets, data tables, KPI cards, minimal padding, grid layout, space-efficient, maximum data visibility',
        'effects': 'Hover tooltips, chart zoom on click, row highlighting on hover, smooth filter animations, data loading spinners',
        'best_for': 'Business intelligence dashboards, financial analytics, enterprise reporting, operational dashboards, data warehousing',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#333333',
        '--fg': '#1E293B',
        '--primary': '#F5F5F5',
        '--secondary': '#333333',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Heat Map & Heatmap Style': {
        'name': 'Heat Map & Heatmap Style',
        'type': 'BI/Analytics',
        'keywords': 'Color-coded grid/matrix, data intensity visualization, geographical heat maps, correlation matrices, cell-based representation, gradient coloring',
        'effects': 'Color gradient transitions on data change, cell highlighting on hover, tooltip reveal on click, smooth color animation',
        'best_for': 'Geographical analysis, performance matrices, correlation analysis, user behavior heatmaps, temperature/intensity data',
        'performance': '⚡ Excellent',
        'accessibility': '⚠ Colorblind considerations',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full (with adjustments)',
        '--bg': '#FF0000',
        '--fg': '#1E293B',
        '--primary': '#0080FF',
        '--secondary': '#FF0000',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Executive Dashboard': {
        'name': 'Executive Dashboard',
        'type': 'BI/Analytics',
        'keywords': 'High-level KPIs, large key metrics, minimal detail, summary view, trend indicators, at-a-glance insights, executive summary',
        'effects': 'KPI value animations (count-up), trend arrow direction animations, metric card hover lift, alert pulse effect',
        'best_for': 'C-suite dashboards, business summary reports, decision-maker dashboards, strategic planning views',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Real-Time Monitoring': {
        'name': 'Real-Time Monitoring',
        'type': 'BI/Analytics',
        'keywords': 'Live data updates, status indicators, alert notifications, streaming data visualization, active monitoring, streaming charts',
        'effects': 'Real-time chart animations, alert pulse/glow, status indicator blink animation, smooth data stream updates, loading effect',
        'best_for': 'System monitoring dashboards, DevOps dashboards, real-time analytics, stock market dashboards, live event tracking',
        'performance': '⚡ Good (real-time load)',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#22C55E',
        '--fg': '#1E293B',
        '--primary': '#FF0000',
        '--secondary': '#FFA500',
        '--accent': '#22C55E',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Drill-Down Analytics': {
        'name': 'Drill-Down Analytics',
        'type': 'BI/Analytics',
        'keywords': 'Hierarchical data exploration, expandable sections, interactive drill-down paths, summary-to-detail flow, context preservation',
        'effects': 'Drill-down expand animations, breadcrumb click transitions, smooth detail reveal, level change smooth, data reload animation',
        'best_for': 'Sales analytics, product analytics, funnel analysis, multi-dimensional data exploration, business intelligence',
        'performance': '⚡ Good',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Comparative Analysis Dashboard': {
        'name': 'Comparative Analysis Dashboard',
        'type': 'BI/Analytics',
        'keywords': 'Side-by-side comparisons, period-over-period metrics, A/B test results, regional comparisons, performance benchmarks',
        'effects': 'Comparison bar animations (grow to value), delta indicator animations (direction arrows), highlight on compare',
        'best_for': 'Period-over-period reporting, A/B test dashboards, market comparison, competitive analysis, regional performance',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Predictive Analytics': {
        'name': 'Predictive Analytics',
        'type': 'BI/Analytics',
        'keywords': 'Forecast lines, confidence intervals, trend projections, scenario modeling, AI-driven insights, anomaly detection visualization',
        'effects': 'Forecast line animation on draw, confidence band fade-in, anomaly pulse alert, smoothing function animations',
        'best_for': 'Forecasting dashboards, anomaly detection systems, trend prediction dashboards, AI-powered analytics, budget planning',
        'performance': '⚠ Good (computation)',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'User Behavior Analytics': {
        'name': 'User Behavior Analytics',
        'type': 'BI/Analytics',
        'keywords': 'Funnel visualization, user flow diagrams, conversion tracking, engagement metrics, user journey mapping, cohort analysis',
        'effects': 'Funnel animation (fill-down), flow diagram animations (connection draw), conversion pulse, engagement bar fill',
        'best_for': 'Conversion funnel analysis, user journey tracking, engagement analytics, cohort analysis, retention tracking',
        'performance': '⚡ Good',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Financial Dashboard': {
        'name': 'Financial Dashboard',
        'type': 'BI/Analytics',
        'keywords': 'Revenue metrics, profit/loss visualization, budget tracking, financial ratios, portfolio performance, cash flow, audit trail',
        'effects': 'Number animations (count-up), trend direction indicators, percentage change animations, profit/loss color transitions',
        'best_for': 'Financial reporting, accounting dashboards, portfolio tracking, budget monitoring, banking analytics',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#003366',
        '--fg': '#1E293B',
        '--primary': '#22C55E',
        '--secondary': '#EF4444',
        '--accent': '#003366',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Sales Intelligence Dashboard': {
        'name': 'Sales Intelligence Dashboard',
        'type': 'BI/Analytics',
        'keywords': 'Deal pipeline, sales metrics, territory performance, sales rep leaderboard, win-loss analysis, quota tracking, forecast accuracy',
        'effects': 'Deal movement animations, metric updates, leaderboard ranking changes, gauge needle movements, status change highlights',
        'best_for': 'CRM dashboards, sales management, opportunity tracking, performance management, quota planning',
        'performance': '⚡ Good',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Neubrutalism': {
        'name': 'Neubrutalism',
        'type': 'General',
        'keywords': 'Bold borders, black outlines, primary colors, thick shadows, no gradients, flat colors, 45° shadows, playful, Gen Z',
        'effects': 'box-shadow: 4px 4px 0 #000, border: 3px solid #000, no gradients, sharp corners (0px), bold typography',
        'best_for': 'Gen Z brands, startups, creative agencies, Figma-style apps, Notion-style interfaces, tech blogs',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#121212',
        '--fg': '#FFFFFF',
        '--primary': '#FFEB3B',
        '--secondary': '#FF5252',
        '--accent': '#2196F3',
        '--border': '#E2E8F0',
        '--radius': '20px',
        '--shadow': '',
        '--border-width': '3px',
        '--blur': '',
        '--glow': '',
    },

    'Bento Box Grid': {
        'name': 'Bento Box Grid',
        'type': 'General',
        'keywords': 'Modular cards, asymmetric grid, varied sizes, Apple-style, dashboard tiles, negative space, clean hierarchy, cards',
        'effects': 'grid-template with varied spans, rounded-xl (16px), subtle shadows, hover scale (1.02), smooth transitions',
        'best_for': 'Dashboards, product pages, portfolios, Apple-style marketing, feature showcases, SaaS',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#F5F5F7',
        '--fg': '#1E293B',
        '--primary': '#FFFFFF',
        '--secondary': '#F5F5F5',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '24px',
        '--shadow': '0 4px 6px rgba(0',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Y2K Aesthetic': {
        'name': 'Y2K Aesthetic',
        'type': 'General',
        'keywords': 'Neon pink, chrome, metallic, bubblegum, iridescent, glossy, retro-futurism, 2000s, futuristic nostalgia',
        'effects': 'linear-gradient metallic, glossy buttons, 3D chrome effects, glow animations, bubble shapes',
        'best_for': 'Fashion brands, music platforms, Gen Z brands, nostalgia marketing, entertainment, youth-focused',
        'performance': '⚠ Good',
        'accessibility': '⚠ Check contrast',
        'light_mode': '✓ Full',
        'dark_mode': '◐ Partial',
        '--bg': '#9400D3',
        '--fg': '#1E293B',
        '--primary': '#FF69B4',
        '--secondary': '#00FFFF',
        '--accent': '#C0C0C0',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Cyberpunk UI': {
        'name': 'Cyberpunk UI',
        'type': 'General',
        'keywords': 'Neon, dark mode, terminal, HUD, sci-fi, glitch, dystopian, futuristic, matrix, tech noir',
        'effects': 'Neon glow (text-shadow), glitch animations (skew/offset), scanlines (::before overlay), terminal fonts',
        'best_for': 'Gaming platforms, tech products, crypto apps, sci-fi applications, developer tools, entertainment',
        'performance': '⚠ Moderate',
        'accessibility': '⚠ Limited (dark+neon)',
        'light_mode': '✗ No',
        'dark_mode': '✓ Only',
        '--bg': '#121212',
        '--fg': '#FFFFFF',
        '--primary': '#00FF00',
        '--secondary': '#FF00FF',
        '--accent': '#00FFFF',
        '--border': '#333333',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Organic Biophilic': {
        'name': 'Organic Biophilic',
        'type': 'General',
        'keywords': 'Nature, organic shapes, green, sustainable, rounded, flowing, wellness, earthy, natural textures',
        'effects': 'Rounded corners (16-24px), organic curves (border-radius variations), natural shadows, flowing SVG shapes',
        'best_for': 'Wellness apps, sustainability brands, eco products, health apps, meditation, organic food brands',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#F5F5DC',
        '--fg': '#1E293B',
        '--primary': '#228B22',
        '--secondary': '#8B4513',
        '--accent': '#87CEEB',
        '--border': '#E2E8F0',
        '--radius': '12px',
        '--shadow': '0 8px 32px rgba(0',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'AI-Native UI': {
        'name': 'AI-Native UI',
        'type': 'General',
        'keywords': 'Chatbot, conversational, voice, assistant, agentic, ambient, minimal chrome, streaming text, AI interactions',
        'effects': 'Typing indicators (3-dot pulse), streaming text animations, pulse animations, context cards, smooth reveals',
        'best_for': 'AI products, chatbots, voice assistants, copilots, AI-powered tools, conversational interfaces',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#F5F5F5',
        '--fg': '#1E293B',
        '--primary': '#6366F1',
        '--secondary': '#10B981',
        '--accent': '#F5F5F5',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Memphis Design': {
        'name': 'Memphis Design',
        'type': 'General',
        'keywords': '80s, geometric, playful, postmodern, shapes, patterns, squiggles, triangles, neon, abstract, bold',
        'effects': 'transform: rotate(), clip-path: polygon(), mix-blend-mode, repeating patterns, bold shapes',
        'best_for': 'Creative agencies, music sites, youth brands, event promotion, artistic portfolios, entertainment',
        'performance': '⚡ Excellent',
        'accessibility': '⚠ Check contrast',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#6A7BB4',
        '--fg': '#1E293B',
        '--primary': '#FF71CE',
        '--secondary': '#FFCE5C',
        '--accent': '#86CCCA',
        '--border': '#E2E8F0',
        '--radius': '20px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Vaporwave': {
        'name': 'Vaporwave',
        'type': 'General',
        'keywords': 'Synthwave, retro-futuristic, 80s-90s, neon, glitch, nostalgic, sunset gradient, dreamy, aesthetic',
        'effects': 'text-shadow glow, linear-gradient, filter: hue-rotate(), glitch animations, retro scan lines',
        'best_for': 'Music platforms, gaming, creative portfolios, tech startups, entertainment, artistic projects',
        'performance': '⚠ Moderate',
        'accessibility': '⚠ Poor (motion)',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Dark focused',
        '--bg': '#B967FF',
        '--fg': '#1E293B',
        '--primary': '#FF71CE',
        '--secondary': '#01CDFE',
        '--accent': '#05FFA1',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Dimensional Layering': {
        'name': 'Dimensional Layering',
        'type': 'General',
        'keywords': 'Depth, overlapping, z-index, layers, 3D, shadows, elevation, floating, cards, spatial hierarchy',
        'effects': 'z-index stacking, box-shadow elevation (4 levels), transform: translateZ(), backdrop-filter, parallax',
        'best_for': 'Dashboards, card layouts, modals, navigation, product showcases, SaaS interfaces',
        'performance': '⚠ Good',
        'accessibility': '⚠ Moderate (SR issues)',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#E0E0E0',
        '--fg': '#1E293B',
        '--primary': '#FFFFFF',
        '--secondary': '#F5F5F5',
        '--accent': '#E0E0E0',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '8px',
        '--glow': '',
    },

    'Exaggerated Minimalism': {
        'name': 'Exaggerated Minimalism',
        'type': 'General',
        'keywords': 'Bold minimalism, oversized typography, high contrast, negative space, loud minimal, statement design',
        'effects': 'font-size: clamp(3rem 10vw 12rem), font-weight: 900, letter-spacing: -0.05em, massive whitespace',
        'best_for': 'Fashion, architecture, portfolios, agency landing pages, luxury brands, editorial',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#000000',
        '--secondary': '#FFFFFF',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Kinetic Typography': {
        'name': 'Kinetic Typography',
        'type': 'General',
        'keywords': 'Motion text, animated type, moving letters, dynamic, typing effect, morphing, scroll-triggered text',
        'effects': '@keyframes text animation, typing effect, background-clip: text, GSAP ScrollTrigger, split text',
        'best_for': 'Hero sections, marketing sites, video platforms, storytelling, creative portfolios, landing pages',
        'performance': '⚠ Moderate',
        'accessibility': '❌ Poor (motion)',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Parallax Storytelling': {
        'name': 'Parallax Storytelling',
        'type': 'General',
        'keywords': 'Scroll-driven, narrative, layered scrolling, immersive, progressive disclosure, cinematic, scroll-triggered',
        'effects': 'transform: translateY(scroll), position: fixed/sticky, perspective: 1px, scroll-triggered animations',
        'best_for': 'Brand storytelling, product launches, case studies, portfolios, annual reports, marketing campaigns',
        'performance': '❌ Poor',
        'accessibility': '❌ Poor (motion)',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Swiss Modernism 2.0': {
        'name': 'Swiss Modernism 2.0',
        'type': 'General',
        'keywords': 'Grid system, Helvetica, modular, asymmetric, international style, rational, clean, mathematical spacing',
        'effects': 'display: grid, grid-template-columns: repeat(12 1fr), gap: 1rem, mathematical ratios, clear hierarchy',
        'best_for': 'Corporate sites, architecture, editorial, SaaS, museums, professional services, documentation',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#F5F5F5',
        '--fg': '#1E293B',
        '--primary': '#000000',
        '--secondary': '#FFFFFF',
        '--accent': '#F5F5F5',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'HUD / Sci-Fi FUI': {
        'name': 'HUD / Sci-Fi FUI',
        'type': 'General',
        'keywords': 'Futuristic, technical, wireframe, neon, data, transparency, iron man, sci-fi, interface',
        'effects': 'Glow effects, scanning animations, ticker text, blinking markers, fine line drawing',
        'best_for': 'Sci-fi games, space tech, cybersecurity, movie props, immersive dashboards',
        'performance': '⚠ Moderate (renders)',
        'accessibility': '⚠ Poor (thin lines)',
        'light_mode': '✓ Low',
        'dark_mode': '✓ Full',
        '--bg': 'rgba(0',
        '--fg': '#1E293B',
        '--primary': '#00FFFF',
        '--secondary': '#0080FF',
        '--accent': '#FF0000',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '0 0 5px',
    },

    'Pixel Art': {
        'name': 'Pixel Art',
        'type': 'General',
        'keywords': 'Retro, 8-bit, 16-bit, gaming, blocky, nostalgic, pixelated, arcade',
        'effects': 'Frame-by-frame sprite animation, blinking cursor, instant transitions, marquee text',
        'best_for': 'Indie games, retro tools, creative portfolios, nostalgia marketing, Web3/NFT',
        'performance': '⚡ Excellent',
        'accessibility': '✓ Good (if contrast ok)',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '0px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Bento Grids': {
        'name': 'Bento Grids',
        'type': 'General',
        'keywords': 'Apple-style, modular, cards, organized, clean, hierarchy, grid, rounded, soft',
        'effects': 'Hover scale (1.02), soft shadow expansion, smooth layout shifts, content reveal',
        'best_for': 'Product features, dashboards, personal sites, marketing summaries, galleries',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#F5F5F7',
        '--fg': '#1E293B',
        '--primary': '#F5F5F7',
        '--secondary': '#FFFFFF',
        '--accent': '#1D1D1F',
        '--border': '#E2E8F0',
        '--radius': '24px',
        '--shadow': 'soft',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Spatial UI (VisionOS)': {
        'name': 'Spatial UI (VisionOS)',
        'type': 'General',
        'keywords': 'Glass, depth, immersion, spatial, translucent, gaze, gesture, apple, vision-pro',
        'effects': 'Parallax depth, dynamic lighting response, gaze-hover effects, smooth scale on focus',
        'best_for': 'Spatial computing apps, VR/AR interfaces, immersive media, futuristic dashboards',
        'performance': '⚠ Moderate (blur cost)',
        'accessibility': '⚠ Contrast risks',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#FFFFFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '40px',
        '--glow': '',
    },

    'E-Ink / Paper': {
        'name': 'E-Ink / Paper',
        'type': 'General',
        'keywords': 'Paper-like, matte, high contrast, texture, reading, calm, slow tech, monochrome',
        'effects': 'No motion blur, distinct page turns, grain/noise texture, sharp transitions (no fade)',
        'best_for': 'Reading apps, digital newspapers, minimal journals, distraction-free writing, slow-living brands',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✗ Low (inverted only)',
        '--bg': '#FDFBF7',
        '--fg': '#1A1A1A',
        '--primary': '#FDFBF7',
        '--secondary': '#F5F5F5',
        '--accent': '#1A1A1A',
        '--border': '#E0E0E0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Gen Z Chaos / Maximalism': {
        'name': 'Gen Z Chaos / Maximalism',
        'type': 'General',
        'keywords': 'Chaos, clutter, stickers, raw, collage, mixed media, loud, internet culture, ironic',
        'effects': 'Marquee scrolls, jitter, sticker layering, GIF overload, random placement, drag-and-drop',
        'best_for': 'Gen Z lifestyle brands, music artists, creative portfolios, viral marketing, fashion',
        'performance': '⚠ Poor (heavy assets)',
        'accessibility': '❌ Poor',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#0000FF',
        '--fg': '#1E293B',
        '--primary': '#FF00FF',
        '--secondary': '#00FF00',
        '--accent': '#FFFF00',
        '--border': '#E2E8F0',
        '--radius': '0px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Biomimetic / Organic 2.0': {
        'name': 'Biomimetic / Organic 2.0',
        'type': 'General',
        'keywords': 'Nature-inspired, cellular, fluid, breathing, generative, algorithms, life-like',
        'effects': 'Breathing animations, fluid morphing, generative growth, physics-based movement',
        'best_for': 'Sustainability tech, biotech, advanced health, meditation, generative art platforms',
        'performance': '⚠ Moderate',
        'accessibility': '✓ Good',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#00FF41',
        '--fg': '#1E293B',
        '--primary': '#FF9999',
        '--secondary': '#00FF41',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Anti-Polish / Raw Aesthetic': {
        'name': 'Anti-Polish / Raw Aesthetic',
        'type': 'General',
        'keywords': 'Hand-drawn, collage, scanned textures, unfinished, imperfect, authentic, human, sketch, raw marks, creative process',
        'effects': 'No smooth transitions, hand-drawn animations, paper texture overlays, jitter effects, sketch reveal',
        'best_for': 'Creative portfolios, artist sites, indie brands, handmade products, authentic storytelling, editorial',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FAFAF8',
        '--fg': '#1E293B',
        '--primary': '#FAFAF8',
        '--secondary': '#4A4A4A',
        '--accent': '#1A1A1A',
        '--border': '#E2E8F0',
        '--radius': '0px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Tactile Digital / Deformable UI': {
        'name': 'Tactile Digital / Deformable UI',
        'type': 'General',
        'keywords': 'Jelly buttons, chrome, clay, squishy, deformable, bouncy, physical, tactile feedback, press response',
        'effects': 'Press deformation (scale + squish), bounce-back (cubic-bezier), material response, haptic-like feedback, spring physics',
        'best_for': 'Modern mobile apps, playful brands, entertainment, gaming UI, consumer products, interactive demos',
        'performance': '⚠ Good',
        'accessibility': '⚠ Motion sensitive',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#87CEEB',
        '--fg': '#1E293B',
        '--primary': '#C0C0C0',
        '--secondary': '#FF9ECD',
        '--accent': '#87CEEB',
        '--border': '#E2E8F0',
        '--radius': '20px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Nature Distilled': {
        'name': 'Nature Distilled',
        'type': 'General',
        'keywords': 'Muted earthy, skin tones, wood, soil, sand, terracotta, warmth, organic materials, handmade warmth',
        'effects': 'Subtle parallax, natural easing (ease-out), texture overlays, grain effects, soft shadows',
        'best_for': 'Wellness brands, sustainable products, artisan goods, organic food, spa/beauty, home decor',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '◐ Partial',
        '--bg': '#F5F0E1',
        '--fg': '#1E293B',
        '--primary': '#C67B5C',
        '--secondary': '#D4C4A8',
        '--accent': '#B5651D',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Interactive Cursor Design': {
        'name': 'Interactive Cursor Design',
        'type': 'General',
        'keywords': 'Custom cursor, cursor as tool, hover effects, cursor feedback, pointer transformation, cursor trail, magnetic cursor',
        'effects': 'Cursor scale on hover, magnetic pull to elements, cursor morphing, trail effects, blend mode cursors, click feedback',
        'best_for': 'Creative portfolios, interactive experiences, agency sites, product showcases, gaming, entertainment',
        'performance': '⚡ Good',
        'accessibility': '⚠ Not for touch/SR',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#409EFF',
        '--secondary': '',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Voice-First Multimodal': {
        'name': 'Voice-First Multimodal',
        'type': 'General',
        'keywords': 'Voice UI, multimodal, audio feedback, conversational, hands-free, ambient, contextual, speech recognition',
        'effects': 'Voice waveform visualization, listening pulse, processing spinner, speak animation, smooth transitions',
        'best_for': 'Voice assistants, accessibility apps, hands-free tools, smart home, automotive UI, cooking apps',
        'performance': '⚡ Excellent',
        'accessibility': '✓ Excellent',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#9B8FBB',
        '--fg': '#1E293B',
        '--primary': '#FAFAFA',
        '--secondary': '#6B8FAF',
        '--accent': '#9B8FBB',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    '3D Product Preview': {
        'name': '3D Product Preview',
        'type': 'General',
        'keywords': '360 product view, rotatable, zoomable, touch-to-spin, AR preview, product configurator, interactive 3D model',
        'effects': 'Drag-to-rotate, pinch-to-zoom, spin animation, AR placement, material switching, smooth orbit controls',
        'best_for': 'E-commerce, furniture, fashion, automotive, electronics, jewelry, product configurators',
        'performance': '❌ Poor (3D rendering)',
        'accessibility': '⚠ Alt content needed',
        'light_mode': '◐ Partial',
        'dark_mode': '◐ Partial',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#E8E8E8',
        '--secondary': '#FFFFFF',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Gradient Mesh / Aurora Evolved': {
        'name': 'Gradient Mesh / Aurora Evolved',
        'type': 'General',
        'keywords': 'Complex gradients, mesh gradients, multi-color blend, aurora effect, flowing colors, iridescent, holographic, prismatic',
        'effects': 'CSS mesh-gradient (experimental), SVG gradients, canvas gradients, smooth color morphing, flowing animation',
        'best_for': 'Hero sections, backgrounds, creative brands, music platforms, fashion, lifestyle, premium products',
        'performance': '⚠ Good',
        'accessibility': '⚠ Text contrast',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#00FF66',
        '--fg': '#1E293B',
        '--primary': '#00FFFF',
        '--secondary': '#FF00FF',
        '--accent': '#FFFF00',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Editorial Grid / Magazine': {
        'name': 'Editorial Grid / Magazine',
        'type': 'General',
        'keywords': 'Magazine layout, asymmetric grid, editorial typography, pull quotes, drop caps, column layout, print-inspired',
        'effects': 'Smooth scroll, reveal on scroll, parallax images, text animations, page-flip transitions',
        'best_for': 'News sites, blogs, magazines, editorial content, long-form articles, journalism, publishing',
        'performance': '⚡ Excellent',
        'accessibility': '✓ WCAG AAA',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Full',
        '--bg': '#FFFFFF',
        '--fg': '#1E293B',
        '--primary': '#000000',
        '--secondary': '#FFFFFF',
        '--accent': '',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Chromatic Aberration / RGB Split': {
        'name': 'Chromatic Aberration / RGB Split',
        'type': 'General',
        'keywords': 'RGB split, color fringing, glitch, retro tech, VHS, analog error, distortion, lens effect',
        'effects': 'RGB offset animation, glitch timing, scan line movement, noise flicker, distortion on hover',
        'best_for': 'Music platforms, gaming, tech brands, creative portfolios, nightlife, entertainment, video platforms',
        'performance': '⚠ Good',
        'accessibility': '⚠ Can cause strain',
        'light_mode': '✓ Full',
        'dark_mode': '✓ Dark preferred',
        '--bg': '#000000',
        '--fg': '#1E293B',
        '--primary': '#FF0000',
        '--secondary': '#00FF00',
        '--accent': '#0000FF',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

    'Vintage Analog / Retro Film': {
        'name': 'Vintage Analog / Retro Film',
        'type': 'General',
        'keywords': 'Film grain, VHS, cassette tape, polaroid, analog warmth, faded colors, light leaks, vintage photography',
        'effects': 'Film grain overlay, VHS tracking effect, polaroid shake, fade-in transitions, light leak animations',
        'best_for': 'Photography portfolios, music/vinyl brands, vintage fashion, nostalgia marketing, film industry, cafes',
        'performance': '⚡ Good',
        'accessibility': '✓ WCAG AA',
        'light_mode': '✓ Full',
        'dark_mode': '◐ Partial',
        '--bg': '#E8B4B8',
        '--fg': '#1E293B',
        '--primary': '#F5E6C8',
        '--secondary': '#D4A574',
        '--accent': '#4A7B7C',
        '--border': '#E2E8F0',
        '--radius': '6px',
        '--shadow': '',
        '--border-width': '1px',
        '--blur': '',
        '--glow': '',
    },

}


# 风格名称列表（有序）
THEME_NAMES: list[str] = list(THEME_TOKENS.keys())

# 总计: {len(THEME_NAMES)} 种风格
